services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  ms-users:
    build: ./ms_users
    container_name: ms-users
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  ms-cart:
    build: ./ms_cart
    container_name: ms-cart
    ports:
      - "9092:9092"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  ms-payment:
    build: ./ms_payment
    container_name: ms-payment
    ports:
      - "9094:9094"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  ms-shipping:
    build: ./ms_shipping
    container_name: ms-shipping
    ports:
      - "9096:9096"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  ms-discount:
    build: ./ms_discount
    container_name: ms-discount
    ports:
      - "9098:9098"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
      - ms-users
      - ms-cart
      - ms-payment
      - ms-shipping
      - ms-discount
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge