services:
  eureka-server:
    build: ./ms_eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  product:
    build: ./product
    container_name: product
    ports:
      - "9000:9000"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  inventory:
    build: ./inventory
    container_name: inventory
    ports:
      - "9002:9002"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
      - product
    networks:
      - microservices-network

  order:
    build: ./order
    container_name: order
    ports:
      - "9003:9003"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
      - product
    networks:
      - microservices-network

  notification:
    build: ./notification
    container_name: notification
    ports:
      - "9099:9099"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  review:
    build: ./review
    container_name: review
    ports:
      - "9097:9097"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
      - product
      - order
    networks:
      - microservices-network

  ms-users:
    build: ./ms_users
    container_name: ms-users
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  ms-cart:
    build: ./ms_cart
    container_name: ms-cart
    ports:
      - "9092:9092"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  ms-payment:
    build: ./ms_payment
    container_name: ms-payment
    ports:
      - "9094:9094"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  ms-shipping:
    build: ./ms_shipping
    container_name: ms-shipping
    ports:
      - "9096:9096"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  ms-discount:
    build: ./ms_discount
    container_name: ms-discount
    ports:
      - "9098:9098"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "9093:9093"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
      - product
      - inventory
      - order
      - notification
      - review
      - ms-users
      - ms-cart
      - ms-payment
      - ms-shipping
      - ms-discount
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
