INSERT INTO product (
    name,
    description,
    price,
    stock,
    care_level,
    category,
    product_status,
    watering_frequency,
    size,
    created_at,
    updated_at
) VALUES
(   'Monstera Deliciosa',
    'Planta de interior con hojas grandes y perforaciones naturales.',
    25.99,
    15,
    'MEDIUM',
    'INTERIOR',
    'ACTIVE',
    'WEEKLY',
    'BIG',
    NOW(),
    NOW()
),
(   'Cactus Asiento de Suegra',
    'Cactus redondo ideal para exteriores con sol directo.',
    12.50,
    40,
    'LOW',
    'SUCCULENT',
    'ACTIVE',
    'BIWEEKLY',
    'SMALL',
    NOW(),
    NOW()
),
(   'Árbol de Jade',
    'Planta suculenta que simboliza la buena suerte.',
    18.00,
    0,
    'LOW',
    'SUCCULENT',
    'OUT_OF_STOCK',
    'WEEKLY',
    'MEDIUM',
    NOW(),
    NOW()
);